# -*- coding: utf-8 -*-
"""why 1.5 is chosen for the IQR for Muliptlication?.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_o-yc93Zdam87EPvL9H6qa2uTSDvomN

The constant 1.5 is chosen for the IQR outlier detection rule because it provides the best balance between being too strict and too lenient, closely aligning with the standard practice for identifying outliers in a normal (Gaussian) distribution ​. The choice of this constant directly controls the sensitivity of the outlier detection method

The 1.5 rule is a method for identifying potential outliers in a dataset by defining a range outside of which data points are considered outliers.

#A data point is flagged as an outlier if it is more than 1.5 times the interquartile range (IQR) below the first quartile Q1 or above the third quartile Q3. The formula to find the outlier boundaries is:#

#Lower Bound = Q1-1.5*IQR
#Upper Bound = Q3+1.5*IQR
"""